config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  mount KepplerAdwords::Engine, :at => '/', as: 'adwords'
  mount KepplerContactUs::Engine, :at => '/', as: 'messages'

  resources :admin, only: :index

  get 'productos/:product', to: 'frontend#show_product'
  get 'productos/:product/:subcategory', to: 'frontend#show_product_by_subcategory'

  scope :admin do
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    
  end


  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'
  mount KepplerCatalogs::Engine, :at => '/', as: 'catalogs'


end

app/models/keppler_catalogs/attachment.rb
#Generado por keppler
require 'elasticsearch/model'
module KepplerCatalogs
  class Attachment < ActiveRecord::Base
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    belongs_to :catalog
    belongs_to :category
    before_save :create_permalink
    before_save :url_iframe_service    
    before_update :update_uploads
    after_update :remove_image_public
    mount_uploader :image, CoverUploader
    validates_presence_of :name, :upload

    
    after_commit on: [:update] do
      puts __elasticsearch__.index_document
    end

    def self.searching(query)
      if query
        self.search(self.query query).records.order(id: :desc)
      else
        self.order(id: :desc)
      end
    end

    def self.query(query)
      { query: { multi_match:  { query: query, fields: [:name, :public] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
    end

    #armar indexado de elasticserch
    def as_indexed_json(options={})
      {
        id: self.id.to_s,
        name:  self.name,
        public:  self.public ? "publicado" : "no--publicado"
      }.as_json
    end

    def create_permalink
      self.permalink = self.name.downcase.parameterize
    end

    def remove_image_public
      if !self.image_url.nil? and self.upload != "1"
        image = File.dirname(Rails.root.join("public"+self.image_url))
        FileUtils.rm_rf(image)
      end
    end
    

    def url_iframe_service
      if !self.url.blank?
        video = self.detected_video_service
        begin
          case video.keys.first
            when "youtube"
              self.url="https://www.youtube.com/embed/"+video.values.first
            when "vimeo"
              self.url="https://player.vimeo.com/video/"+video.values.first
            when "soundcloud"
              detected_soundcloud_sets              
            when "imagen"
            else
              self.url=""
            end
        rescue
          self.url=""
        end
      end
    end

    def detected_soundcloud_sets
      client = Soundcloud.new(:client_id => '83248842d66fa9b18bf565a65ad8a40e')
      begin
        track = client.get('/resolve', :url => self.url)
        if self.url.split(/\W+/).include?("sets")
          self.url="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/#{track.id}&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"
        else
          self.url="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/#{track.id}&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"
        end 
      rescue Soundcloud::ResponseError => e
        
      end
    end

    def detected_video_service      
      if self.upload == "2"
        {"imagen"=>""}
      else
        ["youtube", "soundcloud", "vimeo"].each do |service|    
          if service == "vimeo"
            return { service=>self.url.split("/").last }
          else         
            return { service=>self.url.split((/([\w-]{11})/)).last } if self.url.split(/\W+/).include?(service)
          end
        end
      end
    end

    def update_uploads
      if self.upload == "1"
        self.url = ""
      else
        self.remove_image!
      end   
    end

  end
  #Attachment.import
end

app/models/keppler_catalogs/catalog.rb
#Generado por keppler
require 'elasticsearch/model'
module KepplerCatalogs
  class Catalog < ActiveRecord::Base
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    mount_uploader :cover, CoverUploader
    before_save :create_permalink
    has_many :attachments, :dependent => :destroy
    validates_presence_of :name, :section, :subcategory   

    after_commit on: [:update] do
      puts __elasticsearch__.index_document
    end
    
    def self.searching(query)
      if query
        self.search(self.query query).records.order(id: :desc)
      else
        self.order(id: :desc)
      end
    end

    def self.query(query)
      { query: { multi_match:  { query: query, fields: [:name, :description, :section, :public] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
    end

    def as_indexed_json(options={})
      {
        id: self.id.to_s,
        name:  self.name.to_s,
        description: ActionView::Base.full_sanitizer.sanitize(self.description, tags: []),
        section:  self.section,
        public:  self.public.to_s ? "publicado": "no--publicado"
      }.as_json
    end
    
    def published_files
      self.attachments.where(public: true)
    end

    def published_files_count
      self.attachments.where(public: true).count
    end

    private

    def create_permalink
      self.permalink = self.name.downcase.parameterize
    end

  end
  #Catalog.import
end

app/controllers/keppler_catalogs/attachments_controller.rb
#Generado con Keppler.
require_dependency "keppler_catalogs/application_controller"

module KepplerCatalogs
  class AttachmentsController < ::ApplicationController  
    before_filter :authenticate_user!
    layout 'admin/application'
    load_and_authorize_resource
    before_action :set_attachment, only: [:show, :edit, :update, :destroy]
    before_action :set_catalog

    # GET /attachments
    def index
      attachments = Attachment.searching(@query).where({catalog_id: params[:catalog_id]}).all
      @objects, @total = attachments.page(@current_page), attachments.size
      redirect_to attachments_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
    end

    # GET /attachments/1
    def show
    end

    # GET /attachments/new
    def new
      @attachment = Attachment.new
    end

    # GET /attachments/1/edit
    def edit
    end

    # POST /attachments
    def create
      @attachment = Attachment.new(attachment_params)
      @attachment.catalog_id = params[:catalog_id]

      if @attachment.save
        redirect_to catalog_attachments_path, notice: 'Archivo creado satisfactoriamente.'
      else
        render :new
      end
    end

    # PATCH/PUT /attachments/1
    def update
      if @attachment.update(attachment_params)
        redirect_to catalog_attachments_path, notice: 'Archivo editado satisfactoriamente.'
      else
        render :edit
      end
    end

    # DELETE /attachments/1
    def destroy
      @attachment.destroy
      redirect_to catalog_attachments_url, notice: 'Archivo eliminado satisfactoriamente.'
    end

    def destroy_multiple
      Attachment.destroy redefine_ids(params[:multiple_ids])
      redirect_to catalog_attachments_path(page: @current_page, search: @query), notice: "Archivo eliminados satisfactoriamente" 
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_attachment
        @attachment = Attachment.find(params[:id])
      end

      def set_catalog
        @catalog = Catalog.find_by_id(params[:catalog_id]).nil? ? redirect_to("/404") : Catalog.find(params[:catalog_id])
      end

      # Only allow a trusted parameter "white list" through.
      def attachment_params
        params.require(:attachment).permit(:name, :upload, :description, :image, :url, :target, :public, :permalink, :category_id)
      end
  end
end

app/controllers/keppler_catalogs/catalogs_controller.rb
#Generado con Keppler.
require_dependency "keppler_catalogs/application_controller"

module KepplerCatalogs
  class CatalogsController < ::ApplicationController  
    before_filter :authenticate_user!
    layout 'admin/application'
    load_and_authorize_resource
    before_action :set_catalog, only: [:show, :edit, :update, :destroy]

    # GET /catalogs
    def index
      catalogs = Catalog.searching(@query).all
      @objects, @total = catalogs.page(@current_page), catalogs.size
      redirect_to catalogs_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
    end

    # GET /catalogs/1
    def show
    end

    # GET /catalogs/new
    def new
      @catalog = Catalog.new(public: true)
      @subcategories = []
      KepplerCatalogs::Catalog.all.each do |category|
        @subcategories << category.subcategory
      end
      @subcategorie = @subcategories.uniq!
    end

    # GET /catalogs/1/edit
    def edit      
      @subcategories = []
      KepplerCatalogs::Catalog.all.each do |category|
        @subcategories << category.subcategory
      end
      @subcategorie = @subcategories.uniq!
    end

    # POST /catalogs
    def create
      @catalog = Catalog.new(catalog_params)

      if @catalog.save
        redirect_to catalogs_path, notice: 'Catálogo creado satisfactoriamente.'
      else
        render :new
      end
    end

    # PATCH/PUT /catalogs/1
    def update
      if @catalog.update(catalog_params)
        redirect_to catalogs_path, notice: 'Catálogo editar satisfactoriamente.'
      else
        render :edit
      end
    end

    # DELETE /catalogs/1
    def destroy
      @catalog.destroy
      redirect_to catalogs_url, notice: 'Catálogo eliminar satisfactoriamente.'
    end

    def destroy_multiple
      Catalog.destroy redefine_ids(params[:multiple_ids])
      redirect_to catalogs_path(page: @current_page, search: @query), notice: "Catalogos eliminados satisfactoriamente" 
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_catalog
        @catalog = Catalog.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def catalog_params
        params.require(:catalog).permit(:cover, :name, :description, :section, :subcategory, :priority, :public, :permalink)
      end
  end
end

app/views/keppler_catalogs/catalogs/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.perm_media.css_class("md-light") 
		= "Producto"
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 
			= "Modulo de productos"
		%p{align:"justify"} 
			= t("model.#{controller_name.singularize}.description.body")

app/views/keppler_catalogs/catalogs/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to catalogs_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @catalog do |f|
					.row
					
						= f.input :cover, label: t("model.#{controller_name.singularize}.attributes.cover"), :as => :file_material, label: false, wrapper_html: { class: "file-field" }
						= f.input :name, label: t("model.#{controller_name.singularize}.attributes.name")								
						= f.input :description, label: t("model.#{controller_name.singularize}.attributes.description"), :as => :ckeditor, label: false, input_html: { :ckeditor => { :toolbar => 'short'} }
						= f.input :section, label: t("model.#{controller_name.singularize}.attributes.section"), label: false, collection: KepplerCatalogs.sections,include_blank: "- Selecciona una sección -", input_html: { class: "browser-default" }
						#subcategory_select
							= f.input :subcategory, label: t("model.#{controller_name.singularize}.attributes.subcategory"), collection: @subcategories 
						#subcategory_add
							= f.input :subcategory, label: t("model.#{controller_name.singularize}.attributes.subcategory")
						%a.btn.add_subcategory{title: "Agregar nueva categoria"}
							+
						= f.input :priority, input_html: { min: "0" }
						= f.input :public, label: t("model.#{controller_name.singularize}.attributes.public"), as: :checkbox_material
						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"
- if @catalog.cover.file
	:javascript
		$('.file-path').val("#{@catalog.cover}")

:css
	#subcategory_select, #subcategory_add{
		float: left;
		width: 90% !important;
	}
	.add_subcategory{
		margin-top: 25px;
		font-size: 30px;
	}
- if action_name == "new" or action_name == "create"
	:javascript
		$("#subcategory_select").show();
		$("#subcategory_add").hide();
		var click_point = 0;
		$(".add_subcategory").click(function(){
			if(click_point == 0){
				$("#subcategory_add").show();
				$("#subcategory_select").hide();
				$(".add_subcategory").html("X");
				click_point = 1;
			}else{
				$("#subcategory_select").show();
				$("#subcategory_add").hide();
				$(".add_subcategory").html("+");
				click_point = 0;
			}
		})

- if action_name == "edit" or action_name == "update"
	:javascript
		$("#subcategory_select").remove();

app/views/keppler_catalogs/catalogs/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :index, KepplerCatalogs::Attachment
			= link_to catalog_attachments_path(@catalog), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Ir a imágenes", "data-no-turbolink" => false do
				= material_icon.md_24.perm_media
		- if can? :update, KepplerCatalogs::Catalog
			= link_to edit_catalog_path(@catalog), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar", "data-no-turbolink" => true do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.perm_media.css_class("md-light") 
		= "Producto"
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	= image_tag @catalog.cover
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @catalog.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.section")
			.display-value= @catalog.section
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.subcategory")
			.display-value= @catalog.subcategory
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.public")
			.display-value= @catalog.public? ? "Si" : "No"
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.description")
			.display-value= sanitize(@catalog.description, tags: []).truncate(300)
		%li.list-row
			.display-label Archivos contenidos
			.display-value= @catalog.attachments.count
	

:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/keppler_catalogs/catalogs/_listing.html.haml
%tr{ id: "row-#{catalog.id}" }
	- if can? :destroy_multiple, model
		%td.item-check{style:"width: 10%"}
			= link_to "", catalog_path(catalog), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{catalog.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{catalog.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{catalog.id}" }

	%td{style:"width: 10%"}
		= link_to "", catalog_path(catalog, search: @query), remote: true, class: "show-row"
		%span
			= material_icon.md_24.folder_open
	%td{style:"width: 30%"}
		= link_to "", catalog_path(catalog, search: @query), remote: true, class: "show-row"
		%span
			= catalog.name
	%td{style:"width: 30%"}
		= link_to "", catalog_path(catalog, search: @query), remote: true, class: "show-row"
		%span
			= catalog.section
	%td{style:"width: 30%"}
		= link_to "", catalog_path(catalog, search: @query), remote: true, class: "show-row"
		%span= catalog.public? ? "Publicado" : "No publicado"
								
	%td{style:"width: 5%"}
		= link_to "#", class: "btn-floating waves-effect waves-light btn-flat dropdown-button", "data-activates" => "catalog-options-#{catalog.id}" do
			= material_icon.md_24.more_vert.css_class("md-dark")
		%ul{ id: "catalog-options", class: "dropdown-content dropdow-content-listing", id: "catalog-options-#{catalog.id}"}
			%li
				= link_to 'Ver detallado', catalog_path(catalog)
			%li
				= link_to 'Ir a imágenes', catalog_attachments_path(catalog)
					
					
		

app/views/keppler_catalogs/catalogs/edit.html.haml
= title "Producto - editar | #{@catalog.id}"
= header_information do
	= "Productos"
= render 'form'

app/views/keppler_catalogs/catalogs/index.html.haml
= title("Productos - Listado")
//change header information
= header_information do
	= "Productos"
.listing.col.l9.m12.s12
	- if can? :new, KepplerCatalogs::Catalog
		= link_to new_catalog_path, 'data-no-turbolink' => true, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only"  do
			= material_icon.md_24.add
		= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |catalog|
				= render 'listing', catalog: catalog
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							= t("model.#{controller_name.singularize}.no_found.text")
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, KepplerCatalogs::Catalog
	= link_to new_catalog_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/keppler_catalogs/catalogs/new.html.haml
= title "Producto - Nuevo"
= header_information do
	= "Productos"
= render 'form'

app/views/keppler_catalogs/catalogs/show.html.haml
= title "Producto | #{@catalog.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, model
				= link_to catalog_path(@catalog), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: '¿Estas seguro de querer eliminar?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, model
				= link_to edit_catalog_path(@catalog), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar", "data-no-turbolink" => true do
					= material_icon.md_18.create.css_class("md-dark")
			- if can? :index, KepplerCatalogs::Attachment
				= link_to catalog_attachments_path(@catalog), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Ir a archivos" do
					= material_icon.md_18.perm_media.css_class("md-dark")	
			= link_to catalogs_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card{style: "padding: 0px"}		
			.card-image
				= image_tag @catalog.cover	
			.card-content
				%ul.list
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.name")
						.display-value.fs-body-1.tc-black-2= @catalog.name.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.description")
						.display-value.fs-body-1.tc-black-2= @catalog.description.html_safe
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.section")
						.display-value.fs-body-1.tc-black-2= @catalog.section.to_s.humanize
					%li.list-row
						.display-label= t("model.#{controller_name.singularize}.attributes.public")
						.display-value.fs-body-1.tc-black-2= @catalog.public? ? "Si" : "No"

app/views/keppler_catalogs/catalogs/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@catalog.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");